version: '3'

services:
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-ollama-ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./config:/app/config