[theme]
primaryColor="#1A73E8"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8FAFC"
textColor="#202124"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true

[ui]
hideTopBar = true
